### ISSUE TITLE
translation problem, laravel 5

### ISSUE THREAD

**Issue by juniorowski** [FrozenNode/Laravel-Administrator#876]
Using trans function in config files (eg. in title) causes error:
Fatal error: Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /home/http/bezdomu/vendor/laravel/framework/src/Illuminate/Container/Container.php:776 Stack trace: #0 /home/http/bezdomu/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): ReflectionClass->__construct('log') #1 /home/http/bezdomu/vendor/laravel/framework/src/Illuminate/Container/Container.php(656): Illuminate\Container\Container->build('log', Array) #2 /home/http/bezdomu/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(644): Illuminate\Container\Container->make('log', Array) #3 /home/http/bezdomu/vendor/laravel/framework/src/Illuminate/Container/Container.php(887): Illuminate\Foundation\Application->make('Psr\Log\LoggerI...') #4 /home/http/bezdomu/vendor/laravel/framework/src/Illuminate/Container/Container.php(848): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter)) #5 /home/http/bezdomu/vendor/laravel/framework/src/Illuminate/Container/Container.php(813): Illuminate in /home/http/bezdomu/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 776

**Comment by unrelaxby** [comment]
Have the same problem

**Comment by olenr11** [comment]
too

**Comment by davemathews** [comment]
@juniorowski  can you post your config for me so I can see it and test?

**Comment by max-petrovich** [comment]
'title' => trans('someconfig.title') --- ERROR

**Comment by cathen** [comment]
Have the same problem
I tried using "trans()" in other config file, then got the same err.
Is this a L5 bug?
